FROM node:16.20-bookworm as base

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
        build-essential \
        python3 && \
    rm -fr /var/lib/apt/lists/* && \
    rm -rf /etc/apt/sources.list.d/*
RUN curl -o /usr/bin/solc -fL https://github.com/ethereum/solidity/releases/download/v0.8.4/solc-static-linux
RUN chmod 777 /usr/bin/solc
RUN npm install -g npm@8.19.4
RUN npm install --global --quiet truffle ganache

FROM base as truffle

RUN mkdir -p /home/app
WORKDIR /home/app

COPY package.json /home/app
COPY package-lock.json /home/app

RUN npm install --quiet

RUN chown -R root:root /root
RUN chown -R node:node /root
RUN mkdir -p /root/.local/bin
RUN mkdir -p /home/node/.local/bin
RUN chown -R root:root /home/node/.local/bin
RUN chown -R node:node /home/node/.local/bin

COPY truffle-config.js /home/app
COPY contracts /home/app/contracts
COPY migrations /home/app/migrations/
COPY test /home/app/test/

CMD ["truffle", "version"]

FROM base as ganache

RUN mkdir -p /home/app
WORKDIR /home/app
COPY package*.json /home/app
COPY . /home/app/
RUN npm i --quiet

EXPOSE 3001 8545

ENTRYPOINT [ "npm", "run", "dev" ]
# ENTRYPOINT ["ganache", "--host 0.0.0.0"]

# RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

# WORKDIR /home/node/app
# COPY package*.json ./

# RUN apt-get update && apt-get -y upgrade
# RUN apt-get install -y build-essential libssl-dev libffi-dev software-properties-common python3 python3-pip\
#   && rm -fr /var/lib/apt/lists/* && rm -rf /etc/apt/sources.list.d/*
# RUN curl -o /usr/bin/solc -fL https://github.com/ethereum/solidity/releases/download/v0.8.4/solc-static-linux
# RUN chmod 777 /usr/bin/solc
# RUN npm install -g npm@8.19.4
# RUN npm install --global truffle ganache


# FROM base as ganache

# RUN mkdir -p /home/app
# WORKDIR /home/app

# COPY package*.json /home/app
# # COPY package*.json /home/node/app
# COPY . /home/app/
# RUN npm i --quiet
# RUN npm i express
# RUN chown -R root:root /root
# RUN chown -R node:node /root

# RUN mkdir -p /root/.local/bin
# RUN mkdir -p /home/node/.local/bin
# RUN chown -R root:root /home/node/.local/bin
# RUN chown -R node:node /home/node/.local/bin

# USER node 
# EXPOSE 3001 8545

# ENTRYPOINT [ "npm", "run", "dev" ]
# # ENTRYPOINT ["ganache", "--host 0.0.0.0"]